### ISSUE TITLE
Parsing stops as soon as the first pregap is encountered

### ISSUE THREAD

**Issue by mistydemeo** [leoschwarz/cue_sheet#6]
I have a CD-ROM disc whose second track has a pregap (sample CUE sheet at the end of the end of this post). It looks like parsing stops as soon as that's encountered; the resulting parsed `Tracklist` has only two tracks, and the second track has no indices. I assume that's because of the explicit `break` here: https://github.com/leoschwarz/cue_sheet/blob/master/src/tracklist.rs#L191

```
FILE "disc.img" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 58:41:36
  TRACK 03 AUDIO
    INDEX 00 61:06:08
    INDEX 01 61:08:08
```

**Comment by leoschwarz** [comment]
Fixed in #7.
