### ISSUE TITLE
doesn't treat newlines as command termination

### ISSUE THREAD

**Issue by codyps** [leoschwarz/cue_sheet#9]
Quoting from the hydrogen audio wiki linked in the docs:
> Line breaks must be used between commands

Unfortunately, it appears that this library currently doesn't consider newlines when parsing, resulting in it failing to parse cue sheets that (for example) include commands like `REM DATE 2011-12-22`.

**Comment by leoschwarz** [comment]
I quickly wrote this crate when I needed it, but for compliance with the "standard" I would consider the https://crates.io/crates/cue crate which provides bindings to libcue. I will update the README accordingly.
